[2024-01-04 12:58:19,728,INFO,main,Hello World]
[2024-01-10 17:33:53,760,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 17:33:53,762,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 17:33:53,763,INFO,common,created directory at: artifacts]
[2024-01-10 17:33:53,763,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 17:33:53,764,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:37:04,432,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 17:37:04,433,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 17:37:04,434,INFO,common,created directory at: artifacts]
[2024-01-10 17:37:20,674,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 17:37:20,675,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 17:37:20,676,INFO,common,created directory at: artifacts]
[2024-01-10 17:37:20,676,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 17:39:39,373,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 17:39:39,374,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 17:39:39,375,INFO,common,created directory at: artifacts]
[2024-01-10 17:39:39,375,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 17:39:53,390,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:39:58,327,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:40:12,994,INFO,2427399911,artifacts/data_ingestion/data.zip download! with the following info: 
Server: GitHub.com
Date: Thu, 11 Jan 2024 00:40:12 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
ETag: W/"3bf685dc4c7bd4aa41384006c0758b29"
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events api.githubcopilot.com objects-origin.githubusercontent.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com support.github.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/
Set-Cookie: _gh_sess=8JH42vxCr9NQvIV1Vt5Y9qYwNvDVX6z3trmF59XFwyAUa9mslhMn8z6eCwXq4hMswxWKNAuoAwIq%2FiO6JnX%2F4hAwq20qI%2FYWgpKkT%2FngPFluArnuSRiCiYzqO1broMpZTyEIDUCIislupGvQYyRTUAqVaXtKnJNgsIhEuMJw4uT9Z9lMZtkTYAaOR0HCB9DgyccffxAlq9H8DNhGqd2xMgW8huiY%2F7VAIg4Tz5RDSgXpVryGJW9pwuqrbaQFUWdLdhrZDtK8UqKrD1usM7Mnrw%3D%3D--%2FvVnfEm0mbTVHQEF--HSI2G%2FW22QFatbvCtaBhXg%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.611550845.1704933612; Path=/; Domain=github.com; Expires=Sat, 11 Jan 2025 00:40:12 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Sat, 11 Jan 2025 00:40:12 GMT; HttpOnly; Secure; SameSite=Lax
Accept-Ranges: bytes
Transfer-Encoding: chunked
X-GitHub-Request-Id: 8AA2:0F64:A5A78C:ECFD95:659F38EC
connection: close

]
[2024-01-10 17:41:04,964,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:41:36,121,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:41:58,779,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:42:47,238,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 18:04:40,301,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 18:04:40,310,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 18:04:40,310,INFO,common,created directory at: artifacts]
[2024-01-10 18:04:40,311,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 18:04:58,064,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 18:04:58,065,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 18:04:58,066,INFO,common,created directory at: artifacts]
[2024-01-10 18:04:58,067,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 18:04:58,773,INFO,2427399911,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: BFD4:7D21:20563E:295684:659F3E73
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 01:04:58 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940034-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1704935098.195576,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: bd800cd7527fac978c93003d46d43d3112bee77a
Expires: Thu, 11 Jan 2024 01:09:58 GMT
Source-Age: 70

]
[2024-01-10 18:54:34,494,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-10 18:54:34,494,ERROR,main,DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 9, in <module>
    data_ingestion.main()
TypeError: DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self'
[2024-01-10 18:56:56,453,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-10 18:56:56,453,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 18:56:56,454,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 18:56:56,454,INFO,common,created directory at: artifacts]
[2024-01-10 18:56:56,454,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 18:56:59,291,INFO,data_ingestion,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D402:7676:3DBFB2:4EFC03:659F4AE7
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 01:56:57 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940114-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1704938217.697206,VS0,VE481
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: a7a17cdf7ef73b4b6f458740e3114a92a8247205
Expires: Thu, 11 Jan 2024 02:01:57 GMT
Source-Age: 0

]
[2024-01-10 18:56:59,373,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-11 14:28:32,995,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 14:28:32,996,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:28:32,997,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:28:32,997,INFO,common,created directory at: artifacts]
[2024-01-11 14:28:32,997,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:28:37,590,INFO,data_ingestion,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 21:28:34 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940092-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1705008513.210295,VS0,VE1291
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 675a78c8d1c324d91a0a381f3636212b85b2244d
Expires: Thu, 11 Jan 2024 21:33:34 GMT
Source-Age: 1

]
[2024-01-11 14:28:37,597,ERROR,main,]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_01_data_ingestion.py", line 14, in main
    data_ingestion.extract_zip_file()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_ingestion.py", line 33, in extract_zip_file
    zip_ref.extractall(unzip_path)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1681, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1736, in _extract_member
    shutil.copyfileobj(source, target)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/shutil.py", line 197, in copyfileobj
    buf = fsrc_read(length)
          ^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 955, in read
    data = self._read1(n)
           ^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1023, in _read1
    data += self._read2(n - len(data))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1058, in _read2
    raise EOFError
EOFError
[2024-01-11 14:31:22,293,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 14:31:22,294,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:31:22,294,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:31:22,294,INFO,common,created directory at: artifacts]
[2024-01-11 14:31:22,294,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:31:22,294,INFO,data_ingestion,File already exits of size: ~ 0 KB]
[2024-01-11 14:31:22,295,ERROR,main,File is not a zip file]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_01_data_ingestion.py", line 14, in main
    data_ingestion.extract_zip_file()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-01-11 14:33:13,455,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:33:13,457,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:33:13,464,INFO,common,created directory at: artifacts]
[2024-01-11 14:33:13,466,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:33:20,632,INFO,2427399911,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 21:33:18 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940084-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705008799.735607,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: f51fb7ed4d0fe88105081c0beb19784176de1418
Expires: Thu, 11 Jan 2024 21:38:18 GMT
Source-Age: 285

]
[2024-01-11 14:37:41,145,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:37:41,147,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:37:41,147,INFO,common,created directory at: artifacts]
[2024-01-11 14:37:41,147,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:37:41,148,INFO,2427399911,File already exits of size: ~ 0 KB]
[2024-01-11 14:38:26,116,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:38:26,117,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:38:26,117,INFO,common,created directory at: artifacts]
[2024-01-11 14:38:26,118,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:38:26,118,INFO,2427399911,File already exits of size: ~ 0 KB]
[2024-01-11 14:38:46,880,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:38:46,881,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:38:46,882,INFO,common,created directory at: artifacts]
[2024-01-11 14:38:46,883,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:38:49,723,INFO,2427399911,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 21:38:47 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940046-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705009127.035313,VS0,VE152
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: b00477841ead1e6e51f39d3e6a7a1a72f04af641
Expires: Thu, 11 Jan 2024 21:43:47 GMT
Source-Age: 0

]
[2024-01-11 14:39:57,511,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:39:57,513,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:39:57,513,INFO,common,created directory at: artifacts]
[2024-01-11 14:39:57,514,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:40:00,266,INFO,2427399911,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 21:39:57 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940091-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705009198.621109,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: d8209d5c24aef831ce7490203a92c12482f31972
Expires: Thu, 11 Jan 2024 21:44:57 GMT
Source-Age: 70

]
[2024-01-11 15:03:41,074,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 15:03:41,075,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:03:41,076,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:03:41,076,INFO,common,created directory at: artifacts]
[2024-01-11 15:03:41,076,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 15:03:43,772,INFO,data_ingestion,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 22:03:41 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940097-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705010621.285189,VS0,VE211
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: c3981a9565683116587b035a64841eb49c3cca05
Expires: Thu, 11 Jan 2024 22:08:41 GMT
Source-Age: 0

]
[2024-01-11 15:03:43,780,ERROR,main,]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_01_data_ingestion.py", line 14, in main
    data_ingestion.extract_zip_file()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_ingestion.py", line 33, in extract_zip_file
    zip_ref.extractall(unzip_path)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1681, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1736, in _extract_member
    shutil.copyfileobj(source, target)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/shutil.py", line 197, in copyfileobj
    buf = fsrc_read(length)
          ^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 955, in read
    data = self._read1(n)
           ^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1023, in _read1
    data += self._read2(n - len(data))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1058, in _read2
    raise EOFError
EOFError
[2024-01-11 15:05:38,046,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:05:38,047,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:05:38,047,INFO,common,created directory at: artifacts]
[2024-01-11 15:05:38,048,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 15:05:40,238,INFO,2427399911,artifacts/data_ingestion/data1.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 22:05:38 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940097-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705010738.176006,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 1c9a48c936d825650b564763ea6bf466d0f964e2
Expires: Thu, 11 Jan 2024 22:10:38 GMT
Source-Age: 117

]
[2024-01-11 15:08:20,905,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:08:20,906,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:08:20,907,INFO,common,created directory at: artifacts]
[2024-01-11 15:08:20,907,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 15:08:24,736,INFO,2427399911,artifacts/data_ingestion/data1.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 22:08:21 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940045-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705010901.090178,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 9fd047a0cab6facfebf4f504bef108f5c71c08a6
Expires: Thu, 11 Jan 2024 22:13:21 GMT
Source-Age: 280

]
[2024-01-11 15:09:08,770,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 15:09:08,771,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:09:08,771,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:09:08,771,INFO,common,created directory at: artifacts]
[2024-01-11 15:09:08,772,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 15:09:10,933,INFO,data_ingestion,artifacts/data_ingestion/orgdata.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 22:09:09 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940090-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705010949.021076,VS0,VE205
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 75894036464a3cae3606d53d1bbca31d75218507
Expires: Thu, 11 Jan 2024 22:14:09 GMT
Source-Age: 0

]
[2024-01-11 15:09:11,128,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-11 15:39:01,464,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:39:01,473,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:39:01,473,INFO,common,created directory at: artifacts]
[2024-01-11 15:39:01,473,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 15:39:48,877,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:39:48,878,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:39:48,879,INFO,common,created directory at: artifacts]
[2024-01-11 15:39:48,879,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 15:41:04,554,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:41:04,555,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:41:04,556,INFO,common,created directory at: artifacts]
[2024-01-11 15:41:04,556,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 15:41:47,333,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:41:47,335,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:41:47,336,INFO,common,created directory at: artifacts]
[2024-01-11 15:41:47,336,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 17:53:08,781,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 17:53:08,800,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 17:53:08,801,INFO,common,created directory at: artifacts]
[2024-01-11 17:53:08,801,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 18:24:37,567,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 18:24:37,567,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 18:24:37,568,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 18:24:37,568,INFO,common,created directory at: artifacts]
[2024-01-11 18:24:37,568,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 18:24:45,697,INFO,data_ingestion,artifacts/data_ingestion/orgdata.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 6CB0:40F9:768DC6:96E934:65A094D5
Accept-Ranges: bytes
Date: Fri, 12 Jan 2024 01:24:42 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940029-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1705022678.841129,VS0,VE4656
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 8a17deef5c939b29f0952cb8c73fb52b3536ff01
Expires: Fri, 12 Jan 2024 01:29:42 GMT
Source-Age: 4

]
[2024-01-11 18:24:45,886,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-11 18:24:45,887,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-11 18:24:45,887,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 18:24:45,888,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 18:24:45,888,INFO,common,created directory at: artifacts]
[2024-01-11 18:24:45,888,ERROR,main,ConfigurationManager.get_data_validation_config() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 22, in <module>
    data_validation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_02_data_validation.py", line 12, in main
    data_validation_config = ConfigurationManager.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConfigurationManager.get_data_validation_config() missing 1 required positional argument: 'self'
[2024-01-11 18:29:26,250,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 18:29:26,251,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 18:29:26,251,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 18:29:26,252,INFO,common,created directory at: artifacts]
[2024-01-11 18:29:26,252,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 18:29:30,192,INFO,data_ingestion,artifacts/data_ingestion/orgdata.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 6CB0:40F9:768DC6:96E934:65A094D5
Accept-Ranges: bytes
Date: Fri, 12 Jan 2024 01:29:26 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940052-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705022966.399773,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 2cc0cd604e30ba66aab67e13fb538f338cd1dc2d
Expires: Fri, 12 Jan 2024 01:34:26 GMT
Source-Age: 288

]
[2024-01-11 18:29:30,369,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-11 18:29:30,369,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-11 18:29:30,370,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 18:29:30,370,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 18:29:30,370,INFO,common,created directory at: artifacts]
[2024-01-11 18:29:30,371,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 18:29:30,371,INFO,data_validation,Data Validation Status: True]
[2024-01-11 18:29:30,371,INFO,data_validation,Data Validation Status: True]
[2024-01-11 18:29:30,371,INFO,data_validation,Data Validation Status: True]
[2024-01-11 18:29:30,371,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 20:54:58,475,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:13:28,782,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:13:28,874,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:13:28,875,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:13:28,876,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:13:28,876,INFO,common,created directory at: artifacts]
[2024-01-28 21:13:28,876,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:13:28,876,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:13:29,095,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:13:29,095,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:13:29,096,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:13:29,097,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:13:29,097,INFO,common,created directory at: artifacts]
[2024-01-28 21:13:29,097,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:13:29,097,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:13:29,097,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:13:29,097,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:13:29,097,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:13:29,097,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:13:29,098,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:13:29,098,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:13:29,098,INFO,common,created directory at: artifacts]
[2024-01-28 21:13:29,098,ERROR,main,Argument path_to_directories of type <class 'str'> to <function create_directories at 0x7f491c8f2200> does not match annotation type <class 'list'>]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 15, in main
    data_transformation_config = config.get_data_transformation_config()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/config/configurations.py", line 52, in get_data_transformation_config
    create_directories(config.root_dir)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/ensure/main.py", line 803, in __call__
    raise EnsureError(msg.format(
ensure.main.EnsureError: Argument path_to_directories of type <class 'str'> to <function create_directories at 0x7f491c8f2200> does not match annotation type <class 'list'>
[2024-01-28 21:16:13,019,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:16:13,111,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:16:13,112,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:16:13,112,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:16:13,112,INFO,common,created directory at: artifacts]
[2024-01-28 21:16:13,112,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:16:13,112,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:16:13,298,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:16:13,298,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:16:13,299,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:16:13,299,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:16:13,299,INFO,common,created directory at: artifacts]
[2024-01-28 21:16:13,299,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:16:13,299,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:16:13,300,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:16:13,300,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:16:13,300,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:16:13,300,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:16:13,300,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:16:13,301,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:16:13,301,INFO,common,created directory at: artifacts]
[2024-01-28 21:16:13,301,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:16:15,786,ERROR,main,'dialouge']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    text=example_batch['dialouge'], max_length=1024, truncation=True)
         ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialouge'
[2024-01-28 21:18:09,078,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:18:09,163,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:18:09,164,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:18:09,165,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:18:09,165,INFO,common,created directory at: artifacts]
[2024-01-28 21:18:09,165,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:18:09,165,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:18:09,357,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:18:09,357,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:18:09,358,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:18:09,358,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:18:09,358,INFO,common,created directory at: artifacts]
[2024-01-28 21:18:09,359,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:18:09,359,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:18:09,361,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:18:09,361,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:18:09,361,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:18:09,361,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:18:09,362,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:18:09,362,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:18:09,362,INFO,common,created directory at: artifacts]
[2024-01-28 21:18:09,362,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:18:10,195,ERROR,main,'dialouge']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    text=example_batch['dialouge'], max_length=1024, truncation=True)
         ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialouge'
[2024-01-28 21:20:57,325,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:20:57,435,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:20:57,436,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:20:57,436,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:20:57,436,INFO,common,created directory at: artifacts]
[2024-01-28 21:20:57,436,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:20:57,436,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:20:57,635,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:20:57,635,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:20:57,636,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:20:57,636,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:20:57,636,INFO,common,created directory at: artifacts]
[2024-01-28 21:20:57,636,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:20:57,636,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:20:57,637,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:20:57,637,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:20:57,637,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:20:57,637,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:20:57,638,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:20:57,638,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:20:57,638,INFO,common,created directory at: artifacts]
[2024-01-28 21:20:57,638,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:20:58,604,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    text=example_batch['dialogue'], max_length=1024, truncation=True)
         ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 21:24:08,908,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:24:08,991,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:24:08,992,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:24:08,992,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:24:08,992,INFO,common,created directory at: artifacts]
[2024-01-28 21:24:08,992,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:24:08,992,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:24:09,172,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:24:09,172,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:24:09,173,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:24:09,173,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:24:09,174,INFO,common,created directory at: artifacts]
[2024-01-28 21:24:09,174,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:24:09,174,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:24:09,174,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:24:09,174,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:24:09,174,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:24:09,174,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:24:09,175,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:24:09,175,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:24:09,175,INFO,common,created directory at: artifacts]
[2024-01-28 21:24:09,175,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:24:10,132,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 21:34:23,688,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:34:23,770,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:34:23,771,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:34:23,771,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:34:23,771,INFO,common,created directory at: artifacts]
[2024-01-28 21:34:23,771,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:34:23,771,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:34:23,965,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:34:23,965,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:34:23,966,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:34:23,966,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:34:23,966,INFO,common,created directory at: artifacts]
[2024-01-28 21:34:23,966,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:34:23,966,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:34:23,966,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:34:23,966,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:34:23,966,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:34:23,966,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:34:23,967,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:34:23,967,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:34:23,967,INFO,common,created directory at: artifacts]
[2024-01-28 21:34:23,967,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:34:24,722,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 21:41:26,773,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:41:26,860,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:41:26,861,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:41:26,861,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:41:26,862,INFO,common,created directory at: artifacts]
[2024-01-28 21:41:26,862,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:41:26,862,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:41:27,038,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:41:27,038,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:41:27,039,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:41:27,039,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:41:27,040,INFO,common,created directory at: artifacts]
[2024-01-28 21:41:27,040,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:41:27,040,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:41:27,040,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:41:27,040,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:41:27,040,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:41:27,040,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:41:27,041,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:41:27,041,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:41:27,041,INFO,common,created directory at: artifacts]
[2024-01-28 21:41:27,041,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:41:27,809,ERROR,main,'summary']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['summary'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'summary'
[2024-01-28 21:55:35,547,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:55:35,632,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:55:35,633,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:55:35,633,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:55:35,633,INFO,common,created directory at: artifacts]
[2024-01-28 21:55:35,633,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:55:35,633,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:55:35,822,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:55:35,822,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:55:35,823,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:55:35,823,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:55:35,823,INFO,common,created directory at: artifacts]
[2024-01-28 21:55:35,823,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:55:35,823,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:55:35,823,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:55:35,823,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:55:35,823,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:55:35,823,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:55:35,824,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:55:35,824,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:55:35,824,INFO,common,created directory at: artifacts]
[2024-01-28 21:55:35,824,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:55:36,563,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 21:59:11,925,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:59:12,175,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:59:12,181,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:59:12,181,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:59:12,182,INFO,common,created directory at: artifacts]
[2024-01-28 21:59:12,182,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:59:12,182,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:59:12,362,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:59:12,362,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:59:12,366,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:59:12,366,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:59:12,366,INFO,common,created directory at: artifacts]
[2024-01-28 21:59:12,367,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:59:12,367,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:59:12,367,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:59:12,367,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:59:12,367,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:59:12,367,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 22:01:15,420,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:01:15,422,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:01:15,422,INFO,common,created directory at: artifacts]
[2024-01-28 22:04:24,178,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 22:14:03,442,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 22:22:45,725,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 22:22:45,817,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 22:22:45,818,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:22:45,819,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:22:45,819,INFO,common,created directory at: artifacts]
[2024-01-28 22:22:45,819,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 22:22:45,819,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 22:22:46,003,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 22:22:46,003,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 22:22:46,004,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:22:46,004,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:22:46,004,INFO,common,created directory at: artifacts]
[2024-01-28 22:22:46,004,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 22:22:46,004,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:22:46,005,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:22:46,005,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:22:46,005,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 22:22:46,005,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 22:22:46,006,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:22:46,006,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:22:46,006,INFO,common,created directory at: artifacts]
[2024-01-28 22:22:46,006,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 22:22:50,555,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 22:37:27,861,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 22:37:28,090,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 22:37:28,095,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:37:28,095,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:37:28,096,INFO,common,created directory at: artifacts]
[2024-01-28 22:37:28,096,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 22:37:28,096,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 22:37:28,281,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 22:37:28,281,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 22:37:28,284,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:37:28,285,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:37:28,285,INFO,common,created directory at: artifacts]
[2024-01-28 22:37:28,285,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 22:37:28,285,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:37:28,286,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:37:28,286,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:37:28,286,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 22:37:28,286,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 22:37:36,396,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:37:36,398,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:37:36,398,INFO,common,created directory at: artifacts]
[2024-01-28 22:37:36,398,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:07:22,569,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:07:22,801,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:07:22,803,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:07:22,805,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:07:22,805,INFO,common,created directory at: artifacts]
[2024-01-29 20:07:22,805,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:07:22,805,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:07:23,189,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:07:23,189,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:07:23,191,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:07:23,191,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:07:23,191,INFO,common,created directory at: artifacts]
[2024-01-29 20:07:23,192,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:07:23,192,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:07:23,192,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:07:23,193,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:07:23,193,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:07:23,193,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:07:23,195,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:07:23,195,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:07:23,196,INFO,common,created directory at: artifacts]
[2024-01-29 20:07:23,196,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:07:24,348,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-29 20:08:18,330,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:08:18,739,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:08:18,748,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:08:18,750,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:08:18,750,INFO,common,created directory at: artifacts]
[2024-01-29 20:08:18,750,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:08:18,751,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:08:19,121,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:08:19,121,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:08:19,127,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:08:19,128,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:08:19,128,INFO,common,created directory at: artifacts]
[2024-01-29 20:08:19,128,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:08:19,128,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:08:19,128,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:08:19,129,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:08:19,129,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:08:19,129,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:08:32,816,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:08:32,817,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:08:32,818,INFO,common,created directory at: artifacts]
[2024-01-29 20:08:32,818,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:15:53,768,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:15:54,074,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:15:54,080,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:15:54,082,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:15:54,082,INFO,common,created directory at: artifacts]
[2024-01-29 20:15:54,082,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:15:54,082,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:15:54,410,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:15:54,410,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:15:54,415,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:15:54,416,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:15:54,416,INFO,common,created directory at: artifacts]
[2024-01-29 20:15:54,416,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:15:54,416,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:15:54,417,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:15:54,417,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:15:54,417,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:15:54,417,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:15:59,296,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:15:59,297,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:15:59,297,INFO,common,created directory at: artifacts]
[2024-01-29 20:15:59,297,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:17:39,863,ERROR,main,'dict' object is not callable]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 36, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 42, in convert
    dataset_samsum_pt = dataset_samsum.map(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 868, in map
    {
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 869, in <dictcomp>
    k: dataset.map(
       ^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3470, in _map_single
    batch = apply_function_on_filtered_inputs(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3349, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable
[2024-01-29 20:20:04,842,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:20:04,971,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:20:04,973,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:04,973,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:04,974,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:04,974,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:20:04,974,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:20:05,294,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:20:05,294,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:20:05,296,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:05,297,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:05,297,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:05,297,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:20:05,297,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:05,297,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:05,297,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:05,297,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:20:05,297,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:20:05,299,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:05,300,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:05,300,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:05,300,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:20:10,961,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:20:11,082,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:20:11,084,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:11,084,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:11,084,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:11,085,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:20:11,085,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:20:11,387,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:20:11,387,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:20:11,389,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:11,389,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:11,389,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:11,389,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:20:11,389,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:11,390,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:11,390,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:11,390,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:20:11,390,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:20:11,391,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:11,392,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:11,392,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:11,392,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:20:17,916,ERROR,main,'dict' object is not callable]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 36, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 42, in convert
    dataset_samsum_pt = dataset_samsum.map(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 868, in map
    {
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 869, in <dictcomp>
    k: dataset.map(
       ^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3470, in _map_single
    batch = apply_function_on_filtered_inputs(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3349, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable
[2024-01-29 20:22:57,890,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:22:58,181,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:22:58,187,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:22:58,188,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:22:58,189,INFO,common,created directory at: artifacts]
[2024-01-29 20:22:58,189,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:22:58,189,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:22:58,493,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:22:58,493,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:22:58,499,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:22:58,501,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:22:58,501,INFO,common,created directory at: artifacts]
[2024-01-29 20:22:58,501,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:22:58,501,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:22:58,502,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:22:58,502,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:22:58,502,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:22:58,502,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:22:58,510,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:22:58,511,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:22:58,511,INFO,common,created directory at: artifacts]
[2024-01-29 20:22:58,511,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:32:34,887,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:32:35,015,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:32:35,016,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:35,017,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:35,017,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:35,017,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:32:35,017,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:32:35,319,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:32:35,320,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:32:35,321,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:35,321,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:35,321,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:35,322,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:32:35,322,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:35,322,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:35,322,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:35,322,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:32:35,322,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:32:35,323,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:35,324,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:35,324,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:35,324,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:32:41,611,ERROR,main,'dict' object is not callable]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 36, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 42, in convert
    dataset_samsum_pt = v.map(
                        ^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3470, in _map_single
    batch = apply_function_on_filtered_inputs(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3349, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable
[2024-01-29 20:32:58,045,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:32:58,340,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:32:58,346,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:58,347,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:58,348,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:58,348,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:32:58,348,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:32:58,650,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:32:58,650,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:32:58,656,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:58,657,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:58,657,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:58,657,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:32:58,658,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:58,658,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:58,658,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:58,659,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:32:58,659,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:32:58,666,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:58,667,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:58,668,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:58,668,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:37:03,792,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:37:04,081,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:37:04,087,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:37:04,089,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:37:04,089,INFO,common,created directory at: artifacts]
[2024-01-29 20:37:04,089,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:37:04,089,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:37:04,378,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:37:04,378,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:37:04,383,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:37:04,384,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:37:04,385,INFO,common,created directory at: artifacts]
[2024-01-29 20:37:04,385,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:37:04,385,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:37:04,385,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:37:04,386,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:37:04,386,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:37:04,386,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:37:04,394,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:37:04,395,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:37:04,396,INFO,common,created directory at: artifacts]
[2024-01-29 20:37:04,396,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:41:31,345,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:41:31,693,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:41:31,702,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:41:31,704,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:41:31,704,INFO,common,created directory at: artifacts]
[2024-01-29 20:41:31,705,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:41:31,705,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:41:32,009,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:41:32,009,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:41:32,014,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:41:32,015,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:41:32,015,INFO,common,created directory at: artifacts]
[2024-01-29 20:41:32,016,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:41:32,016,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:41:32,016,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:41:32,017,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:41:32,017,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:41:32,017,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:41:32,025,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:41:32,027,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:41:32,027,INFO,common,created directory at: artifacts]
[2024-01-29 20:41:32,027,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:41:56,729,ERROR,main,"Column train not in the dataset. Current columns in the dataset: ['id', 'dialogue', 'summary']"]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 36, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 45, in convert
    self.convert_examples_to_features(example_batch=v, set=k), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 35, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 23, in convert_examples_to_features
    example_batch[set]['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 2800, in __getitem__
    return self._getitem(key)
           ^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 2784, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/formatting/formatting.py", line 580, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/formatting/formatting.py", line 520, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column train not in the dataset. Current columns in the dataset: ['id', 'dialogue', 'summary']"
[2024-01-29 20:44:49,027,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:44:49,317,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:44:49,323,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:44:49,324,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:44:49,325,INFO,common,created directory at: artifacts]
[2024-01-29 20:44:49,325,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:44:49,325,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:44:49,643,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:44:49,643,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:44:49,649,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:44:49,650,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:44:49,650,INFO,common,created directory at: artifacts]
[2024-01-29 20:44:49,650,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:44:49,650,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:44:49,651,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:44:49,651,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:44:49,651,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:44:49,651,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:44:49,658,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:44:49,659,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:44:49,660,INFO,common,created directory at: artifacts]
[2024-01-29 20:44:49,660,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:46:00,311,ERROR,main,'dict' object is not callable]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 36, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 44, in convert
    dataset_samsum_pt = tmp.map(
                        ^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 868, in map
    {
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 869, in <dictcomp>
    k: dataset.map(
       ^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3470, in _map_single
    batch = apply_function_on_filtered_inputs(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3349, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable
[2024-01-29 20:52:24,957,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:52:25,262,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:52:25,268,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:52:25,270,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:52:25,270,INFO,common,created directory at: artifacts]
[2024-01-29 20:52:25,270,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:52:25,270,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:52:25,568,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:52:25,568,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:52:25,574,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:52:25,575,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:52:25,575,INFO,common,created directory at: artifacts]
[2024-01-29 20:52:25,575,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:52:25,576,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:52:25,576,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:52:25,577,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:52:25,577,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:52:25,577,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:52:25,583,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:52:25,585,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:52:25,585,INFO,common,created directory at: artifacts]
[2024-01-29 20:52:25,585,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:52:50,065,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-01-29 20:56:26,163,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:56:26,463,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:56:26,470,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:56:26,472,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:56:26,472,INFO,common,created directory at: artifacts]
[2024-01-29 20:56:26,472,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:56:26,472,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:56:26,796,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:56:26,796,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:56:26,801,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:56:26,802,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:56:26,802,INFO,common,created directory at: artifacts]
[2024-01-29 20:56:26,803,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:56:26,803,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:56:26,803,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:56:26,803,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:56:26,803,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:56:26,803,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:56:26,814,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:56:26,816,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:56:26,816,INFO,common,created directory at: artifacts]
[2024-01-29 20:56:26,817,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:57:04,898,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:57:05,195,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:57:05,202,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:57:05,203,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:57:05,203,INFO,common,created directory at: artifacts]
[2024-01-29 20:57:05,204,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:57:05,204,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:57:05,514,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:57:05,514,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:57:05,519,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:57:05,520,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:57:05,520,INFO,common,created directory at: artifacts]
[2024-01-29 20:57:05,520,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:57:05,520,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:57:05,520,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:57:05,521,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:57:05,521,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:57:05,521,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:57:05,526,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:57:05,527,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:57:05,527,INFO,common,created directory at: artifacts]
[2024-01-29 20:57:05,527,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:58:12,443,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-01-30 20:21:17,562,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-30 20:21:17,705,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-30 20:21:17,706,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-30 20:21:17,706,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-30 20:21:17,706,INFO,common,created directory at: artifacts]
[2024-01-30 20:21:17,707,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-30 20:21:27,492,INFO,data_ingestion,artifacts/data_ingestion/orgdata.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 55F2:50C4:9DF756:D4B888:65B9BCAD
Accept-Ranges: bytes
Date: Wed, 31 Jan 2024 03:21:19 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940051-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1706671278.999431,VS0,VE1034
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 6c1fa63bb21bb540b55b2491efca464c0c73e6b3
Expires: Wed, 31 Jan 2024 03:26:19 GMT
Source-Age: 1

]
[2024-01-30 20:21:27,673,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-30 20:21:27,674,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-30 20:21:27,674,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-30 20:21:27,675,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-30 20:21:27,675,INFO,common,created directory at: artifacts]
[2024-01-30 20:21:27,675,INFO,common,created directory at: artifacts/data_validation]
[2024-01-30 20:21:27,675,INFO,data_validation,Data Validation Status: True]
[2024-01-30 20:21:27,675,INFO,data_validation,Data Validation Status: True]
[2024-01-30 20:21:27,675,INFO,data_validation,Data Validation Status: True]
[2024-01-30 20:21:27,675,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-30 20:21:27,675,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-30 20:21:27,676,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-30 20:21:27,676,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-30 20:21:27,676,INFO,common,created directory at: artifacts]
[2024-01-30 20:21:27,676,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-30 20:21:29,963,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
