[2024-01-04 12:58:19,728,INFO,main,Hello World]
[2024-01-10 17:33:53,760,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 17:33:53,762,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 17:33:53,763,INFO,common,created directory at: artifacts]
[2024-01-10 17:33:53,763,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 17:33:53,764,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:37:04,432,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 17:37:04,433,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 17:37:04,434,INFO,common,created directory at: artifacts]
[2024-01-10 17:37:20,674,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 17:37:20,675,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 17:37:20,676,INFO,common,created directory at: artifacts]
[2024-01-10 17:37:20,676,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 17:39:39,373,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 17:39:39,374,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 17:39:39,375,INFO,common,created directory at: artifacts]
[2024-01-10 17:39:39,375,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 17:39:53,390,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:39:58,327,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:40:12,994,INFO,2427399911,artifacts/data_ingestion/data.zip download! with the following info: 
Server: GitHub.com
Date: Thu, 11 Jan 2024 00:40:12 GMT
Content-Type: text/html; charset=utf-8
Vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
ETag: W/"3bf685dc4c7bd4aa41384006c0758b29"
Cache-Control: max-age=0, private, must-revalidate
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 0
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: default-src 'none'; base-uri 'self'; child-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/; connect-src 'self' uploads.github.com www.githubstatus.com collector.github.com raw.githubusercontent.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events api.githubcopilot.com objects-origin.githubusercontent.com *.actions.githubusercontent.com wss://*.actions.githubusercontent.com productionresultssa0.blob.core.windows.net/ productionresultssa1.blob.core.windows.net/ productionresultssa2.blob.core.windows.net/ productionresultssa3.blob.core.windows.net/ productionresultssa4.blob.core.windows.net/ productionresultssa5.blob.core.windows.net/ productionresultssa6.blob.core.windows.net/ productionresultssa7.blob.core.windows.net/ productionresultssa8.blob.core.windows.net/ productionresultssa9.blob.core.windows.net/ github-production-repository-image-32fea6.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com insights.github.com wss://alive.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com objects-origin.githubusercontent.com; frame-ancestors 'none'; frame-src viewscreen.githubusercontent.com notebooks.githubusercontent.com support.github.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com objects.githubusercontent.com secured-user-images.githubusercontent.com/ user-images.githubusercontent.com/ private-user-images.githubusercontent.com opengraph.githubassets.com github-production-user-asset-6210df.s3.amazonaws.com customer-stories-feed.github.com spotlights-feed.github.com objects-origin.githubusercontent.com *.githubusercontent.com; manifest-src 'self'; media-src github.com user-images.githubusercontent.com/ secured-user-images.githubusercontent.com/ private-user-images.githubusercontent.com github-production-user-asset-6210df.s3.amazonaws.com gist.github.com; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com; upgrade-insecure-requests; worker-src github.com/assets-cdn/worker/ gist.github.com/assets-cdn/worker/
Set-Cookie: _gh_sess=8JH42vxCr9NQvIV1Vt5Y9qYwNvDVX6z3trmF59XFwyAUa9mslhMn8z6eCwXq4hMswxWKNAuoAwIq%2FiO6JnX%2F4hAwq20qI%2FYWgpKkT%2FngPFluArnuSRiCiYzqO1broMpZTyEIDUCIislupGvQYyRTUAqVaXtKnJNgsIhEuMJw4uT9Z9lMZtkTYAaOR0HCB9DgyccffxAlq9H8DNhGqd2xMgW8huiY%2F7VAIg4Tz5RDSgXpVryGJW9pwuqrbaQFUWdLdhrZDtK8UqKrD1usM7Mnrw%3D%3D--%2FvVnfEm0mbTVHQEF--HSI2G%2FW22QFatbvCtaBhXg%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax
Set-Cookie: _octo=GH1.1.611550845.1704933612; Path=/; Domain=github.com; Expires=Sat, 11 Jan 2025 00:40:12 GMT; Secure; SameSite=Lax
Set-Cookie: logged_in=no; Path=/; Domain=github.com; Expires=Sat, 11 Jan 2025 00:40:12 GMT; HttpOnly; Secure; SameSite=Lax
Accept-Ranges: bytes
Transfer-Encoding: chunked
X-GitHub-Request-Id: 8AA2:0F64:A5A78C:ECFD95:659F38EC
connection: close

]
[2024-01-10 17:41:04,964,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:41:36,121,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:41:58,779,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 17:42:47,238,INFO,2427399911,File already exits of size: ~ 133 KB]
[2024-01-10 18:04:40,301,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 18:04:40,310,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 18:04:40,310,INFO,common,created directory at: artifacts]
[2024-01-10 18:04:40,311,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 18:04:58,064,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 18:04:58,065,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 18:04:58,066,INFO,common,created directory at: artifacts]
[2024-01-10 18:04:58,067,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 18:04:58,773,INFO,2427399911,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: BFD4:7D21:20563E:295684:659F3E73
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 01:04:58 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940034-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1704935098.195576,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: bd800cd7527fac978c93003d46d43d3112bee77a
Expires: Thu, 11 Jan 2024 01:09:58 GMT
Source-Age: 70

]
[2024-01-10 18:54:34,494,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-10 18:54:34,494,ERROR,main,DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 9, in <module>
    data_ingestion.main()
TypeError: DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self'
[2024-01-10 18:56:56,453,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-10 18:56:56,453,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-10 18:56:56,454,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-10 18:56:56,454,INFO,common,created directory at: artifacts]
[2024-01-10 18:56:56,454,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-10 18:56:59,291,INFO,data_ingestion,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: D402:7676:3DBFB2:4EFC03:659F4AE7
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 01:56:57 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940114-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1704938217.697206,VS0,VE481
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: a7a17cdf7ef73b4b6f458740e3114a92a8247205
Expires: Thu, 11 Jan 2024 02:01:57 GMT
Source-Age: 0

]
[2024-01-10 18:56:59,373,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-11 14:28:32,995,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 14:28:32,996,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:28:32,997,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:28:32,997,INFO,common,created directory at: artifacts]
[2024-01-11 14:28:32,997,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:28:37,590,INFO,data_ingestion,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 21:28:34 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940092-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1705008513.210295,VS0,VE1291
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 675a78c8d1c324d91a0a381f3636212b85b2244d
Expires: Thu, 11 Jan 2024 21:33:34 GMT
Source-Age: 1

]
[2024-01-11 14:28:37,597,ERROR,main,]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_01_data_ingestion.py", line 14, in main
    data_ingestion.extract_zip_file()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_ingestion.py", line 33, in extract_zip_file
    zip_ref.extractall(unzip_path)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1681, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1736, in _extract_member
    shutil.copyfileobj(source, target)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/shutil.py", line 197, in copyfileobj
    buf = fsrc_read(length)
          ^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 955, in read
    data = self._read1(n)
           ^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1023, in _read1
    data += self._read2(n - len(data))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1058, in _read2
    raise EOFError
EOFError
[2024-01-11 14:31:22,293,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 14:31:22,294,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:31:22,294,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:31:22,294,INFO,common,created directory at: artifacts]
[2024-01-11 14:31:22,294,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:31:22,294,INFO,data_ingestion,File already exits of size: ~ 0 KB]
[2024-01-11 14:31:22,295,ERROR,main,File is not a zip file]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_01_data_ingestion.py", line 14, in main
    data_ingestion.extract_zip_file()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1302, in __init__
    self._RealGetContents()
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1369, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-01-11 14:33:13,455,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:33:13,457,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:33:13,464,INFO,common,created directory at: artifacts]
[2024-01-11 14:33:13,466,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:33:20,632,INFO,2427399911,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 21:33:18 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940084-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705008799.735607,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: f51fb7ed4d0fe88105081c0beb19784176de1418
Expires: Thu, 11 Jan 2024 21:38:18 GMT
Source-Age: 285

]
[2024-01-11 14:37:41,145,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:37:41,147,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:37:41,147,INFO,common,created directory at: artifacts]
[2024-01-11 14:37:41,147,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:37:41,148,INFO,2427399911,File already exits of size: ~ 0 KB]
[2024-01-11 14:38:26,116,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:38:26,117,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:38:26,117,INFO,common,created directory at: artifacts]
[2024-01-11 14:38:26,118,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:38:26,118,INFO,2427399911,File already exits of size: ~ 0 KB]
[2024-01-11 14:38:46,880,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:38:46,881,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:38:46,882,INFO,common,created directory at: artifacts]
[2024-01-11 14:38:46,883,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:38:49,723,INFO,2427399911,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 21:38:47 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940046-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705009127.035313,VS0,VE152
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: b00477841ead1e6e51f39d3e6a7a1a72f04af641
Expires: Thu, 11 Jan 2024 21:43:47 GMT
Source-Age: 0

]
[2024-01-11 14:39:57,511,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 14:39:57,513,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 14:39:57,513,INFO,common,created directory at: artifacts]
[2024-01-11 14:39:57,514,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 14:40:00,266,INFO,2427399911,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 21:39:57 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940091-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705009198.621109,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: d8209d5c24aef831ce7490203a92c12482f31972
Expires: Thu, 11 Jan 2024 21:44:57 GMT
Source-Age: 70

]
[2024-01-11 15:03:41,074,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 15:03:41,075,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:03:41,076,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:03:41,076,INFO,common,created directory at: artifacts]
[2024-01-11 15:03:41,076,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 15:03:43,772,INFO,data_ingestion,artifacts/data_ingestion/data.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 22:03:41 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940097-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705010621.285189,VS0,VE211
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: c3981a9565683116587b035a64841eb49c3cca05
Expires: Thu, 11 Jan 2024 22:08:41 GMT
Source-Age: 0

]
[2024-01-11 15:03:43,780,ERROR,main,]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 9, in <module>
    data_ingestion.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_01_data_ingestion.py", line 14, in main
    data_ingestion.extract_zip_file()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_ingestion.py", line 33, in extract_zip_file
    zip_ref.extractall(unzip_path)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1681, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1736, in _extract_member
    shutil.copyfileobj(source, target)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/shutil.py", line 197, in copyfileobj
    buf = fsrc_read(length)
          ^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 955, in read
    data = self._read1(n)
           ^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1023, in _read1
    data += self._read2(n - len(data))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/zipfile.py", line 1058, in _read2
    raise EOFError
EOFError
[2024-01-11 15:05:38,046,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:05:38,047,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:05:38,047,INFO,common,created directory at: artifacts]
[2024-01-11 15:05:38,048,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 15:05:40,238,INFO,2427399911,artifacts/data_ingestion/data1.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 22:05:38 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940097-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705010738.176006,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 1c9a48c936d825650b564763ea6bf466d0f964e2
Expires: Thu, 11 Jan 2024 22:10:38 GMT
Source-Age: 117

]
[2024-01-11 15:08:20,905,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:08:20,906,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:08:20,907,INFO,common,created directory at: artifacts]
[2024-01-11 15:08:20,907,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 15:08:24,736,INFO,2427399911,artifacts/data_ingestion/data1.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 22:08:21 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940045-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705010901.090178,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 9fd047a0cab6facfebf4f504bef108f5c71c08a6
Expires: Thu, 11 Jan 2024 22:13:21 GMT
Source-Age: 280

]
[2024-01-11 15:09:08,770,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 15:09:08,771,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:09:08,771,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:09:08,771,INFO,common,created directory at: artifacts]
[2024-01-11 15:09:08,772,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 15:09:10,933,INFO,data_ingestion,artifacts/data_ingestion/orgdata.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 828E:40F9:70AEE5:8F8407:65A05D80
Accept-Ranges: bytes
Date: Thu, 11 Jan 2024 22:09:09 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940090-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705010949.021076,VS0,VE205
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 75894036464a3cae3606d53d1bbca31d75218507
Expires: Thu, 11 Jan 2024 22:14:09 GMT
Source-Age: 0

]
[2024-01-11 15:09:11,128,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-11 15:39:01,464,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:39:01,473,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:39:01,473,INFO,common,created directory at: artifacts]
[2024-01-11 15:39:01,473,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 15:39:48,877,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:39:48,878,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:39:48,879,INFO,common,created directory at: artifacts]
[2024-01-11 15:39:48,879,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 15:41:04,554,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:41:04,555,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:41:04,556,INFO,common,created directory at: artifacts]
[2024-01-11 15:41:04,556,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 15:41:47,333,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 15:41:47,335,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 15:41:47,336,INFO,common,created directory at: artifacts]
[2024-01-11 15:41:47,336,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 17:53:08,781,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 17:53:08,800,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 17:53:08,801,INFO,common,created directory at: artifacts]
[2024-01-11 17:53:08,801,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 18:24:37,567,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 18:24:37,567,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 18:24:37,568,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 18:24:37,568,INFO,common,created directory at: artifacts]
[2024-01-11 18:24:37,568,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 18:24:45,697,INFO,data_ingestion,artifacts/data_ingestion/orgdata.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 6CB0:40F9:768DC6:96E934:65A094D5
Accept-Ranges: bytes
Date: Fri, 12 Jan 2024 01:24:42 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940029-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1705022678.841129,VS0,VE4656
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 8a17deef5c939b29f0952cb8c73fb52b3536ff01
Expires: Fri, 12 Jan 2024 01:29:42 GMT
Source-Age: 4

]
[2024-01-11 18:24:45,886,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-11 18:24:45,887,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-11 18:24:45,887,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 18:24:45,888,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 18:24:45,888,INFO,common,created directory at: artifacts]
[2024-01-11 18:24:45,888,ERROR,main,ConfigurationManager.get_data_validation_config() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 22, in <module>
    data_validation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_02_data_validation.py", line 12, in main
    data_validation_config = ConfigurationManager.get_data_validation_config()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConfigurationManager.get_data_validation_config() missing 1 required positional argument: 'self'
[2024-01-11 18:29:26,250,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-11 18:29:26,251,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 18:29:26,251,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 18:29:26,252,INFO,common,created directory at: artifacts]
[2024-01-11 18:29:26,252,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-11 18:29:30,192,INFO,data_ingestion,artifacts/data_ingestion/orgdata.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 6CB0:40F9:768DC6:96E934:65A094D5
Accept-Ranges: bytes
Date: Fri, 12 Jan 2024 01:29:26 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940052-LAX
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1705022966.399773,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 2cc0cd604e30ba66aab67e13fb538f338cd1dc2d
Expires: Fri, 12 Jan 2024 01:34:26 GMT
Source-Age: 288

]
[2024-01-11 18:29:30,369,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-11 18:29:30,369,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-11 18:29:30,370,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-11 18:29:30,370,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-11 18:29:30,370,INFO,common,created directory at: artifacts]
[2024-01-11 18:29:30,371,INFO,common,created directory at: artifacts/data_validation]
[2024-01-11 18:29:30,371,INFO,data_validation,Data Validation Status: True]
[2024-01-11 18:29:30,371,INFO,data_validation,Data Validation Status: True]
[2024-01-11 18:29:30,371,INFO,data_validation,Data Validation Status: True]
[2024-01-11 18:29:30,371,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 20:54:58,475,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:13:28,782,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:13:28,874,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:13:28,875,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:13:28,876,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:13:28,876,INFO,common,created directory at: artifacts]
[2024-01-28 21:13:28,876,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:13:28,876,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:13:29,095,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:13:29,095,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:13:29,096,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:13:29,097,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:13:29,097,INFO,common,created directory at: artifacts]
[2024-01-28 21:13:29,097,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:13:29,097,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:13:29,097,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:13:29,097,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:13:29,097,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:13:29,097,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:13:29,098,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:13:29,098,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:13:29,098,INFO,common,created directory at: artifacts]
[2024-01-28 21:13:29,098,ERROR,main,Argument path_to_directories of type <class 'str'> to <function create_directories at 0x7f491c8f2200> does not match annotation type <class 'list'>]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 15, in main
    data_transformation_config = config.get_data_transformation_config()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/config/configurations.py", line 52, in get_data_transformation_config
    create_directories(config.root_dir)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/ensure/main.py", line 803, in __call__
    raise EnsureError(msg.format(
ensure.main.EnsureError: Argument path_to_directories of type <class 'str'> to <function create_directories at 0x7f491c8f2200> does not match annotation type <class 'list'>
[2024-01-28 21:16:13,019,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:16:13,111,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:16:13,112,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:16:13,112,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:16:13,112,INFO,common,created directory at: artifacts]
[2024-01-28 21:16:13,112,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:16:13,112,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:16:13,298,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:16:13,298,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:16:13,299,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:16:13,299,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:16:13,299,INFO,common,created directory at: artifacts]
[2024-01-28 21:16:13,299,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:16:13,299,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:16:13,300,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:16:13,300,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:16:13,300,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:16:13,300,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:16:13,300,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:16:13,301,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:16:13,301,INFO,common,created directory at: artifacts]
[2024-01-28 21:16:13,301,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:16:15,786,ERROR,main,'dialouge']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    text=example_batch['dialouge'], max_length=1024, truncation=True)
         ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialouge'
[2024-01-28 21:18:09,078,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:18:09,163,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:18:09,164,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:18:09,165,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:18:09,165,INFO,common,created directory at: artifacts]
[2024-01-28 21:18:09,165,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:18:09,165,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:18:09,357,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:18:09,357,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:18:09,358,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:18:09,358,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:18:09,358,INFO,common,created directory at: artifacts]
[2024-01-28 21:18:09,359,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:18:09,359,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:18:09,361,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:18:09,361,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:18:09,361,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:18:09,361,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:18:09,362,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:18:09,362,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:18:09,362,INFO,common,created directory at: artifacts]
[2024-01-28 21:18:09,362,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:18:10,195,ERROR,main,'dialouge']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    text=example_batch['dialouge'], max_length=1024, truncation=True)
         ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialouge'
[2024-01-28 21:20:57,325,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:20:57,435,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:20:57,436,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:20:57,436,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:20:57,436,INFO,common,created directory at: artifacts]
[2024-01-28 21:20:57,436,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:20:57,436,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:20:57,635,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:20:57,635,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:20:57,636,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:20:57,636,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:20:57,636,INFO,common,created directory at: artifacts]
[2024-01-28 21:20:57,636,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:20:57,636,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:20:57,637,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:20:57,637,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:20:57,637,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:20:57,637,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:20:57,638,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:20:57,638,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:20:57,638,INFO,common,created directory at: artifacts]
[2024-01-28 21:20:57,638,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:20:58,604,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    text=example_batch['dialogue'], max_length=1024, truncation=True)
         ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 21:24:08,908,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:24:08,991,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:24:08,992,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:24:08,992,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:24:08,992,INFO,common,created directory at: artifacts]
[2024-01-28 21:24:08,992,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:24:08,992,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:24:09,172,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:24:09,172,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:24:09,173,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:24:09,173,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:24:09,174,INFO,common,created directory at: artifacts]
[2024-01-28 21:24:09,174,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:24:09,174,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:24:09,174,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:24:09,174,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:24:09,174,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:24:09,174,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:24:09,175,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:24:09,175,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:24:09,175,INFO,common,created directory at: artifacts]
[2024-01-28 21:24:09,175,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:24:10,132,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 21:34:23,688,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:34:23,770,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:34:23,771,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:34:23,771,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:34:23,771,INFO,common,created directory at: artifacts]
[2024-01-28 21:34:23,771,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:34:23,771,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:34:23,965,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:34:23,965,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:34:23,966,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:34:23,966,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:34:23,966,INFO,common,created directory at: artifacts]
[2024-01-28 21:34:23,966,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:34:23,966,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:34:23,966,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:34:23,966,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:34:23,966,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:34:23,966,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:34:23,967,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:34:23,967,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:34:23,967,INFO,common,created directory at: artifacts]
[2024-01-28 21:34:23,967,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:34:24,722,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 21:41:26,773,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:41:26,860,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:41:26,861,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:41:26,861,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:41:26,862,INFO,common,created directory at: artifacts]
[2024-01-28 21:41:26,862,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:41:26,862,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:41:27,038,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:41:27,038,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:41:27,039,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:41:27,039,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:41:27,040,INFO,common,created directory at: artifacts]
[2024-01-28 21:41:27,040,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:41:27,040,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:41:27,040,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:41:27,040,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:41:27,040,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:41:27,040,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:41:27,041,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:41:27,041,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:41:27,041,INFO,common,created directory at: artifacts]
[2024-01-28 21:41:27,041,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:41:27,809,ERROR,main,'summary']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['summary'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'summary'
[2024-01-28 21:55:35,547,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:55:35,632,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:55:35,633,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:55:35,633,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:55:35,633,INFO,common,created directory at: artifacts]
[2024-01-28 21:55:35,633,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:55:35,633,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:55:35,822,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:55:35,822,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:55:35,823,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:55:35,823,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:55:35,823,INFO,common,created directory at: artifacts]
[2024-01-28 21:55:35,823,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:55:35,823,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:55:35,823,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:55:35,823,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:55:35,823,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:55:35,823,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 21:55:35,824,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:55:35,824,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:55:35,824,INFO,common,created directory at: artifacts]
[2024-01-28 21:55:35,824,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 21:55:36,563,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 21:59:11,925,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 21:59:12,175,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 21:59:12,181,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:59:12,181,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:59:12,182,INFO,common,created directory at: artifacts]
[2024-01-28 21:59:12,182,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 21:59:12,182,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 21:59:12,362,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 21:59:12,362,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 21:59:12,366,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 21:59:12,366,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 21:59:12,366,INFO,common,created directory at: artifacts]
[2024-01-28 21:59:12,367,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 21:59:12,367,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:59:12,367,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:59:12,367,INFO,data_validation,Data Validation Status: True]
[2024-01-28 21:59:12,367,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 21:59:12,367,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 22:01:15,420,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:01:15,422,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:01:15,422,INFO,common,created directory at: artifacts]
[2024-01-28 22:04:24,178,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 22:14:03,442,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 22:22:45,725,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 22:22:45,817,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 22:22:45,818,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:22:45,819,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:22:45,819,INFO,common,created directory at: artifacts]
[2024-01-28 22:22:45,819,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 22:22:45,819,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 22:22:46,003,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 22:22:46,003,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 22:22:46,004,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:22:46,004,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:22:46,004,INFO,common,created directory at: artifacts]
[2024-01-28 22:22:46,004,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 22:22:46,004,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:22:46,005,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:22:46,005,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:22:46,005,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 22:22:46,005,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 22:22:46,006,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:22:46,006,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:22:46,006,INFO,common,created directory at: artifacts]
[2024-01-28 22:22:46,006,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-28 22:22:50,555,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-28 22:37:27,861,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-28 22:37:28,090,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-28 22:37:28,095,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:37:28,095,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:37:28,096,INFO,common,created directory at: artifacts]
[2024-01-28 22:37:28,096,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-28 22:37:28,096,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-28 22:37:28,281,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-28 22:37:28,281,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-28 22:37:28,284,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:37:28,285,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:37:28,285,INFO,common,created directory at: artifacts]
[2024-01-28 22:37:28,285,INFO,common,created directory at: artifacts/data_validation]
[2024-01-28 22:37:28,285,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:37:28,286,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:37:28,286,INFO,data_validation,Data Validation Status: True]
[2024-01-28 22:37:28,286,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-28 22:37:28,286,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-28 22:37:36,396,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-28 22:37:36,398,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-28 22:37:36,398,INFO,common,created directory at: artifacts]
[2024-01-28 22:37:36,398,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:07:22,569,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:07:22,801,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:07:22,803,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:07:22,805,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:07:22,805,INFO,common,created directory at: artifacts]
[2024-01-29 20:07:22,805,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:07:22,805,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:07:23,189,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:07:23,189,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:07:23,191,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:07:23,191,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:07:23,191,INFO,common,created directory at: artifacts]
[2024-01-29 20:07:23,192,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:07:23,192,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:07:23,192,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:07:23,193,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:07:23,193,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:07:23,193,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:07:23,195,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:07:23,195,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:07:23,196,INFO,common,created directory at: artifacts]
[2024-01-29 20:07:23,196,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:07:24,348,ERROR,main,'dialogue']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 35, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 39, in convert
    self.convert_examples_to_features(example_batch=dataset_samsum), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 34, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 22, in convert_examples_to_features
    example_batch['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'dialogue'
[2024-01-29 20:08:18,330,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:08:18,739,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:08:18,748,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:08:18,750,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:08:18,750,INFO,common,created directory at: artifacts]
[2024-01-29 20:08:18,750,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:08:18,751,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:08:19,121,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:08:19,121,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:08:19,127,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:08:19,128,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:08:19,128,INFO,common,created directory at: artifacts]
[2024-01-29 20:08:19,128,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:08:19,128,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:08:19,128,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:08:19,129,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:08:19,129,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:08:19,129,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:08:32,816,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:08:32,817,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:08:32,818,INFO,common,created directory at: artifacts]
[2024-01-29 20:08:32,818,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:15:53,768,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:15:54,074,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:15:54,080,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:15:54,082,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:15:54,082,INFO,common,created directory at: artifacts]
[2024-01-29 20:15:54,082,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:15:54,082,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:15:54,410,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:15:54,410,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:15:54,415,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:15:54,416,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:15:54,416,INFO,common,created directory at: artifacts]
[2024-01-29 20:15:54,416,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:15:54,416,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:15:54,417,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:15:54,417,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:15:54,417,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:15:54,417,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:15:59,296,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:15:59,297,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:15:59,297,INFO,common,created directory at: artifacts]
[2024-01-29 20:15:59,297,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:17:39,863,ERROR,main,'dict' object is not callable]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 36, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 42, in convert
    dataset_samsum_pt = dataset_samsum.map(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 868, in map
    {
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 869, in <dictcomp>
    k: dataset.map(
       ^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3470, in _map_single
    batch = apply_function_on_filtered_inputs(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3349, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable
[2024-01-29 20:20:04,842,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:20:04,971,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:20:04,973,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:04,973,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:04,974,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:04,974,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:20:04,974,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:20:05,294,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:20:05,294,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:20:05,296,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:05,297,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:05,297,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:05,297,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:20:05,297,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:05,297,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:05,297,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:05,297,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:20:05,297,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:20:05,299,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:05,300,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:05,300,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:05,300,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:20:10,961,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:20:11,082,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:20:11,084,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:11,084,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:11,084,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:11,085,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:20:11,085,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:20:11,387,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:20:11,387,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:20:11,389,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:11,389,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:11,389,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:11,389,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:20:11,389,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:11,390,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:11,390,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:20:11,390,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:20:11,390,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:20:11,391,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:20:11,392,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:20:11,392,INFO,common,created directory at: artifacts]
[2024-01-29 20:20:11,392,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:20:17,916,ERROR,main,'dict' object is not callable]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 36, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 42, in convert
    dataset_samsum_pt = dataset_samsum.map(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 868, in map
    {
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 869, in <dictcomp>
    k: dataset.map(
       ^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3470, in _map_single
    batch = apply_function_on_filtered_inputs(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3349, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable
[2024-01-29 20:22:57,890,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:22:58,181,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:22:58,187,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:22:58,188,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:22:58,189,INFO,common,created directory at: artifacts]
[2024-01-29 20:22:58,189,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:22:58,189,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:22:58,493,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:22:58,493,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:22:58,499,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:22:58,501,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:22:58,501,INFO,common,created directory at: artifacts]
[2024-01-29 20:22:58,501,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:22:58,501,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:22:58,502,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:22:58,502,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:22:58,502,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:22:58,502,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:22:58,510,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:22:58,511,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:22:58,511,INFO,common,created directory at: artifacts]
[2024-01-29 20:22:58,511,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:32:34,887,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:32:35,015,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:32:35,016,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:35,017,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:35,017,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:35,017,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:32:35,017,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:32:35,319,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:32:35,320,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:32:35,321,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:35,321,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:35,321,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:35,322,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:32:35,322,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:35,322,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:35,322,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:35,322,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:32:35,322,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:32:35,323,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:35,324,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:35,324,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:35,324,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:32:41,611,ERROR,main,'dict' object is not callable]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 36, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 42, in convert
    dataset_samsum_pt = v.map(
                        ^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3470, in _map_single
    batch = apply_function_on_filtered_inputs(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3349, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable
[2024-01-29 20:32:58,045,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:32:58,340,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:32:58,346,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:58,347,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:58,348,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:58,348,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:32:58,348,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:32:58,650,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:32:58,650,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:32:58,656,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:58,657,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:58,657,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:58,657,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:32:58,658,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:58,658,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:58,658,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:32:58,659,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:32:58,659,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:32:58,666,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:32:58,667,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:32:58,668,INFO,common,created directory at: artifacts]
[2024-01-29 20:32:58,668,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:37:03,792,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:37:04,081,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:37:04,087,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:37:04,089,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:37:04,089,INFO,common,created directory at: artifacts]
[2024-01-29 20:37:04,089,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:37:04,089,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:37:04,378,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:37:04,378,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:37:04,383,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:37:04,384,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:37:04,385,INFO,common,created directory at: artifacts]
[2024-01-29 20:37:04,385,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:37:04,385,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:37:04,385,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:37:04,386,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:37:04,386,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:37:04,386,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:37:04,394,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:37:04,395,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:37:04,396,INFO,common,created directory at: artifacts]
[2024-01-29 20:37:04,396,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:41:31,345,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:41:31,693,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:41:31,702,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:41:31,704,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:41:31,704,INFO,common,created directory at: artifacts]
[2024-01-29 20:41:31,705,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:41:31,705,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:41:32,009,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:41:32,009,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:41:32,014,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:41:32,015,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:41:32,015,INFO,common,created directory at: artifacts]
[2024-01-29 20:41:32,016,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:41:32,016,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:41:32,016,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:41:32,017,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:41:32,017,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:41:32,017,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:41:32,025,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:41:32,027,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:41:32,027,INFO,common,created directory at: artifacts]
[2024-01-29 20:41:32,027,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:41:56,729,ERROR,main,"Column train not in the dataset. Current columns in the dataset: ['id', 'dialogue', 'summary']"]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 36, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 45, in convert
    self.convert_examples_to_features(example_batch=v, set=k), batched=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 35, in convert_examples_to_features
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 23, in convert_examples_to_features
    example_batch[set]['dialogue'], max_length=1024, truncation=True)
    ~~~~~~~~~~~~~^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 2800, in __getitem__
    return self._getitem(key)
           ^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 2784, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/formatting/formatting.py", line 580, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/formatting/formatting.py", line 520, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column train not in the dataset. Current columns in the dataset: ['id', 'dialogue', 'summary']"
[2024-01-29 20:44:49,027,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:44:49,317,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:44:49,323,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:44:49,324,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:44:49,325,INFO,common,created directory at: artifacts]
[2024-01-29 20:44:49,325,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:44:49,325,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:44:49,643,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:44:49,643,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:44:49,649,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:44:49,650,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:44:49,650,INFO,common,created directory at: artifacts]
[2024-01-29 20:44:49,650,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:44:49,650,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:44:49,651,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:44:49,651,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:44:49,651,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:44:49,651,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:44:49,658,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:44:49,659,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:44:49,660,INFO,common,created directory at: artifacts]
[2024-01-29 20:44:49,660,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:46:00,311,ERROR,main,'dict' object is not callable]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 36, in <module>
    data_transformation.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_03_data_transformation.py", line 18, in main
    data_transformation.convert()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/data_transformation.py", line 44, in convert
    dataset_samsum_pt = tmp.map(
                        ^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 868, in map
    {
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 869, in <dictcomp>
    k: dataset.map(
       ^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 592, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3093, in map
    for rank, done, content in Dataset._map_single(**dataset_kwargs):
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3470, in _map_single
    batch = apply_function_on_filtered_inputs(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 3349, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'dict' object is not callable
[2024-01-29 20:52:24,957,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:52:25,262,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:52:25,268,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:52:25,270,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:52:25,270,INFO,common,created directory at: artifacts]
[2024-01-29 20:52:25,270,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:52:25,270,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:52:25,568,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:52:25,568,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:52:25,574,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:52:25,575,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:52:25,575,INFO,common,created directory at: artifacts]
[2024-01-29 20:52:25,575,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:52:25,576,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:52:25,576,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:52:25,577,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:52:25,577,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:52:25,577,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:52:25,583,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:52:25,585,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:52:25,585,INFO,common,created directory at: artifacts]
[2024-01-29 20:52:25,585,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:52:50,065,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-01-29 20:56:26,163,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:56:26,463,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:56:26,470,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:56:26,472,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:56:26,472,INFO,common,created directory at: artifacts]
[2024-01-29 20:56:26,472,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:56:26,472,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:56:26,796,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:56:26,796,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:56:26,801,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:56:26,802,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:56:26,802,INFO,common,created directory at: artifacts]
[2024-01-29 20:56:26,803,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:56:26,803,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:56:26,803,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:56:26,803,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:56:26,803,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:56:26,803,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:56:26,814,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:56:26,816,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:56:26,816,INFO,common,created directory at: artifacts]
[2024-01-29 20:56:26,817,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:57:04,898,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-29 20:57:05,195,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-29 20:57:05,202,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:57:05,203,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:57:05,203,INFO,common,created directory at: artifacts]
[2024-01-29 20:57:05,204,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-29 20:57:05,204,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-01-29 20:57:05,514,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-29 20:57:05,514,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-29 20:57:05,519,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:57:05,520,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:57:05,520,INFO,common,created directory at: artifacts]
[2024-01-29 20:57:05,520,INFO,common,created directory at: artifacts/data_validation]
[2024-01-29 20:57:05,520,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:57:05,520,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:57:05,521,INFO,data_validation,Data Validation Status: True]
[2024-01-29 20:57:05,521,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-29 20:57:05,521,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-29 20:57:05,526,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-29 20:57:05,527,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-29 20:57:05,527,INFO,common,created directory at: artifacts]
[2024-01-29 20:57:05,527,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-29 20:58:12,443,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-01-30 20:21:17,562,INFO,config,PyTorch version 2.1.2 available.]
[2024-01-30 20:21:17,705,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-01-30 20:21:17,706,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-30 20:21:17,706,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-30 20:21:17,706,INFO,common,created directory at: artifacts]
[2024-01-30 20:21:17,707,INFO,common,created directory at: artifacts/data_ingestion]
[2024-01-30 20:21:27,492,INFO,data_ingestion,artifacts/data_ingestion/orgdata.zip download! with the following info: 
Connection: close
Content-Length: 23627009
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "2e7409b328d118a1d37018be788babf8bf9640386387da766ac100e96efa3b93"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 55F2:50C4:9DF756:D4B888:65B9BCAD
Accept-Ranges: bytes
Date: Wed, 31 Jan 2024 03:21:19 GMT
Via: 1.1 varnish
X-Served-By: cache-lax-kwhp1940051-LAX
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1706671278.999431,VS0,VE1034
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 6c1fa63bb21bb540b55b2491efca464c0c73e6b3
Expires: Wed, 31 Jan 2024 03:26:19 GMT
Source-Age: 1

]
[2024-01-30 20:21:27,673,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-01-30 20:21:27,674,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-01-30 20:21:27,674,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-30 20:21:27,675,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-30 20:21:27,675,INFO,common,created directory at: artifacts]
[2024-01-30 20:21:27,675,INFO,common,created directory at: artifacts/data_validation]
[2024-01-30 20:21:27,675,INFO,data_validation,Data Validation Status: True]
[2024-01-30 20:21:27,675,INFO,data_validation,Data Validation Status: True]
[2024-01-30 20:21:27,675,INFO,data_validation,Data Validation Status: True]
[2024-01-30 20:21:27,675,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-01-30 20:21:27,675,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-01-30 20:21:27,676,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-01-30 20:21:27,676,INFO,common,yaml file params.yaml loaded successfully]
[2024-01-30 20:21:27,676,INFO,common,created directory at: artifacts]
[2024-01-30 20:21:27,676,INFO,common,created directory at: artifacts/data_transformation]
[2024-01-30 20:21:29,963,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-02-01 17:47:58,832,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 17:47:59,002,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 17:47:59,003,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 17:47:59,004,INFO,common,created directory at: artifacts]
[2024-02-01 17:47:59,004,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 16:54:43,580,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 16:54:43,741,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 16:54:43,742,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 16:54:43,743,INFO,common,created directory at: artifacts]
[2024-02-01 16:54:43,743,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 17:01:34,216,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 17:01:34,380,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 17:01:34,381,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 17:01:34,381,INFO,common,created directory at: artifacts]
[2024-02-01 17:01:34,381,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 17:10:50,366,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 17:10:50,608,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 17:10:50,609,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 17:10:50,610,INFO,common,created directory at: artifacts]
[2024-02-01 17:10:50,610,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 17:15:58,029,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 17:15:58,299,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 17:15:58,301,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 17:15:58,301,INFO,common,created directory at: artifacts]
[2024-02-01 17:15:58,301,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 17:17:27,586,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 17:17:27,852,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 17:17:27,854,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 17:17:27,854,INFO,common,created directory at: artifacts]
[2024-02-01 17:17:27,854,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 17:18:00,418,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 17:18:00,679,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 17:18:00,680,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 17:18:00,680,INFO,common,created directory at: artifacts]
[2024-02-01 17:18:00,680,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 17:37:49,116,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 17:37:49,408,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 17:37:49,409,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 17:37:49,410,INFO,common,created directory at: artifacts]
[2024-02-01 17:37:49,410,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 17:40:04,661,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 17:40:04,945,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 17:40:04,946,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 17:40:04,947,INFO,common,created directory at: artifacts]
[2024-02-01 17:40:04,947,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 17:41:20,822,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 17:41:21,097,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 17:41:21,098,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 17:41:21,099,INFO,common,created directory at: artifacts]
[2024-02-01 17:41:21,099,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 17:53:32,563,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 17:53:32,812,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 17:53:32,813,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 17:53:32,814,INFO,common,created directory at: artifacts]
[2024-02-01 17:53:32,814,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 19:40:18,140,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 19:40:18,683,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-02-01 19:40:18,684,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:40:18,685,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:40:18,685,INFO,common,created directory at: artifacts]
[2024-02-01 19:40:18,685,INFO,common,created directory at: artifacts/data_ingestion]
[2024-02-01 19:40:18,685,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-02-01 19:40:18,892,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-02-01 19:40:18,892,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-02-01 19:40:18,893,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:40:18,894,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:40:18,894,INFO,common,created directory at: artifacts]
[2024-02-01 19:40:18,894,INFO,common,created directory at: artifacts/data_validation]
[2024-02-01 19:40:18,894,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:40:18,894,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:40:18,894,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:40:18,894,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-02-01 19:40:18,894,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-02-01 19:40:18,895,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:40:18,895,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:40:18,896,INFO,common,created directory at: artifacts]
[2024-02-01 19:40:18,896,INFO,common,created directory at: artifacts/data_transformation]
[2024-02-01 19:40:21,206,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-02-01 19:40:21,206,INFO,main,>>>>>> Stage Model Training Stage started <<<<<<]
[2024-02-01 19:40:21,207,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:40:21,208,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:40:21,208,INFO,common,created directory at: artifacts]
[2024-02-01 19:40:21,208,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 19:40:30,889,ERROR,main,No executable batch size found, reached zero.]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 48, in <module>
    model_trainer.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 19, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 17, in main
    model_trainer.train()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_trainer.py", line 51, in train
    trainer.train()
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/accelerate/utils/memory.py", line 134, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.
[2024-02-01 19:41:05,087,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 19:41:05,661,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-02-01 19:41:05,662,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:41:05,663,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:41:05,663,INFO,common,created directory at: artifacts]
[2024-02-01 19:41:05,663,INFO,common,created directory at: artifacts/data_ingestion]
[2024-02-01 19:41:05,663,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-02-01 19:41:05,854,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-02-01 19:41:05,854,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-02-01 19:41:05,855,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:41:05,855,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:41:05,855,INFO,common,created directory at: artifacts]
[2024-02-01 19:41:05,855,INFO,common,created directory at: artifacts/data_validation]
[2024-02-01 19:41:05,856,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:41:05,856,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:41:05,856,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:41:05,856,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-02-01 19:41:05,856,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-02-01 19:41:05,857,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:41:05,857,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:41:05,857,INFO,common,created directory at: artifacts]
[2024-02-01 19:41:05,857,INFO,common,created directory at: artifacts/data_transformation]
[2024-02-01 19:41:06,782,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-02-01 19:41:06,782,INFO,main,>>>>>> Stage Model Training Stage started <<<<<<]
[2024-02-01 19:41:06,784,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:41:06,784,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:41:06,784,INFO,common,created directory at: artifacts]
[2024-02-01 19:41:06,784,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 19:41:15,674,ERROR,main,CUDA out of memory. Tried to allocate 376.00 MiB. GPU 0 has a total capacty of 3.82 GiB of which 335.69 MiB is free. Including non-PyTorch memory, this process has 3.42 GiB memory in use. Of the allocated memory 2.51 GiB is allocated by PyTorch, and 32.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 48, in <module>
    model_trainer.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 19, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 17, in main
    model_trainer.train()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_trainer.py", line 52, in train
    trainer.train()
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 2781, in training_step
    self.accelerator.backward(loss)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/accelerate/accelerator.py", line 1964, in backward
    loss.backward(**kwargs)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 376.00 MiB. GPU 0 has a total capacty of 3.82 GiB of which 335.69 MiB is free. Including non-PyTorch memory, this process has 3.42 GiB memory in use. Of the allocated memory 2.51 GiB is allocated by PyTorch, and 32.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2024-02-01 19:43:01,437,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 19:43:02,044,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-02-01 19:43:02,046,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:43:02,047,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:43:02,047,INFO,common,created directory at: artifacts]
[2024-02-01 19:43:02,047,INFO,common,created directory at: artifacts/data_ingestion]
[2024-02-01 19:43:02,047,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-02-01 19:43:02,241,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-02-01 19:43:02,241,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-02-01 19:43:02,242,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:43:02,243,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:43:02,243,INFO,common,created directory at: artifacts]
[2024-02-01 19:43:02,243,INFO,common,created directory at: artifacts/data_validation]
[2024-02-01 19:43:02,243,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:43:02,243,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:43:02,243,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:43:02,244,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-02-01 19:43:02,244,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-02-01 19:43:02,244,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:43:02,245,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:43:02,245,INFO,common,created directory at: artifacts]
[2024-02-01 19:43:02,245,INFO,common,created directory at: artifacts/data_transformation]
[2024-02-01 19:43:03,215,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-02-01 19:43:03,215,INFO,main,>>>>>> Stage Model Training Stage started <<<<<<]
[2024-02-01 19:43:03,216,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:43:03,216,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:43:03,217,INFO,common,created directory at: artifacts]
[2024-02-01 19:43:03,217,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 19:43:12,234,ERROR,main,CUDA out of memory. Tried to allocate 376.00 MiB. GPU 0 has a total capacty of 3.82 GiB of which 335.69 MiB is free. Including non-PyTorch memory, this process has 3.42 GiB memory in use. Of the allocated memory 2.51 GiB is allocated by PyTorch, and 32.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 48, in <module>
    model_trainer.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 19, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 17, in main
    model_trainer.train()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_trainer.py", line 53, in train
    trainer.train()
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 2781, in training_step
    self.accelerator.backward(loss)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/accelerate/accelerator.py", line 1964, in backward
    loss.backward(**kwargs)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 376.00 MiB. GPU 0 has a total capacty of 3.82 GiB of which 335.69 MiB is free. Including non-PyTorch memory, this process has 3.42 GiB memory in use. Of the allocated memory 2.51 GiB is allocated by PyTorch, and 32.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2024-02-01 19:43:47,665,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-01 19:43:48,507,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-02-01 19:43:48,508,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:43:48,509,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:43:48,509,INFO,common,created directory at: artifacts]
[2024-02-01 19:43:48,509,INFO,common,created directory at: artifacts/data_ingestion]
[2024-02-01 19:43:48,509,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-02-01 19:43:50,108,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-02-01 19:43:50,108,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-02-01 19:43:50,109,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:43:50,109,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:43:50,109,INFO,common,created directory at: artifacts]
[2024-02-01 19:43:50,109,INFO,common,created directory at: artifacts/data_validation]
[2024-02-01 19:43:50,110,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:43:50,110,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:43:50,110,INFO,data_validation,Data Validation Status: True]
[2024-02-01 19:43:50,110,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-02-01 19:43:50,110,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-02-01 19:43:50,111,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:43:50,111,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:43:50,112,INFO,common,created directory at: artifacts]
[2024-02-01 19:43:50,112,INFO,common,created directory at: artifacts/data_transformation]
[2024-02-01 19:43:50,835,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-02-01 19:43:50,835,INFO,main,>>>>>> Stage Model Training Stage started <<<<<<]
[2024-02-01 19:43:50,836,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-01 19:43:50,837,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-01 19:43:50,837,INFO,common,created directory at: artifacts]
[2024-02-01 19:43:50,837,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-01 19:43:59,499,ERROR,main,CUDA out of memory. Tried to allocate 376.00 MiB. GPU 0 has a total capacty of 3.82 GiB of which 335.69 MiB is free. Including non-PyTorch memory, this process has 3.42 GiB memory in use. Of the allocated memory 2.51 GiB is allocated by PyTorch, and 32.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 48, in <module>
    model_trainer.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 19, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 17, in main
    model_trainer.train()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_trainer.py", line 53, in train
    trainer.train()
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 2781, in training_step
    self.accelerator.backward(loss)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/accelerate/accelerator.py", line 1964, in backward
    loss.backward(**kwargs)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 376.00 MiB. GPU 0 has a total capacty of 3.82 GiB of which 335.69 MiB is free. Including non-PyTorch memory, this process has 3.42 GiB memory in use. Of the allocated memory 2.51 GiB is allocated by PyTorch, and 32.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2024-02-02 20:04:52,457,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-02 20:04:52,703,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-02 20:04:52,704,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-02 20:04:52,704,INFO,common,created directory at: artifacts]
[2024-02-02 20:04:52,704,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-02 20:06:34,908,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-02 20:07:17,362,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-02 20:07:17,364,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-02 20:07:17,365,INFO,common,created directory at: artifacts]
[2024-02-02 20:09:41,428,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-02 20:09:41,430,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-02 20:09:41,431,INFO,common,created directory at: artifacts]
[2024-02-02 20:09:41,440,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 13:19:40,600,INFO,server,Started server process [24768]]
[2024-02-15 13:19:40,601,INFO,on,Waiting for application startup.]
[2024-02-15 13:19:40,601,INFO,on,Application startup complete.]
[2024-02-15 13:19:40,601,INFO,server,Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)]
[2024-02-15 13:21:11,739,ERROR,h11_impl,Exception in ASGI application
]
Traceback (most recent call last):
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/app.py", line 46, in predict_route
    raise e
  File "/home/dephinate/ASU/TextSummarization/app.py", line 42, in predict_route
    pred_pipe = PredictionPipeline()
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/prediction.py", line 8, in __init__
    self.config = ConfigurationManager.get_model_evaluation_config()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConfigurationManager.get_model_evaluation_config() missing 1 required positional argument: 'self'
[2024-02-15 13:21:36,118,INFO,server,Shutting down]
[2024-02-15 13:21:36,219,INFO,on,Waiting for application shutdown.]
[2024-02-15 13:21:36,219,INFO,on,Application shutdown complete.]
[2024-02-15 13:21:36,219,INFO,server,Finished server process [24768]]
[2024-02-15 13:40:07,663,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 13:40:09,307,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-02-15 13:40:09,309,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 13:40:09,310,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 13:40:09,310,INFO,common,created directory at: artifacts]
[2024-02-15 13:40:09,310,INFO,common,created directory at: artifacts/data_ingestion]
[2024-02-15 13:40:09,310,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-02-15 13:40:09,507,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-02-15 13:40:09,507,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-02-15 13:40:09,508,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 13:40:09,509,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 13:40:09,509,INFO,common,created directory at: artifacts]
[2024-02-15 13:40:09,509,INFO,common,created directory at: artifacts/data_validation]
[2024-02-15 13:40:09,509,INFO,data_validation,Data Validation Status: True]
[2024-02-15 13:40:09,509,INFO,data_validation,Data Validation Status: True]
[2024-02-15 13:40:09,509,INFO,data_validation,Data Validation Status: True]
[2024-02-15 13:40:09,509,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-02-15 13:40:09,509,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-02-15 13:40:09,510,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 13:40:09,511,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 13:40:09,511,INFO,common,created directory at: artifacts]
[2024-02-15 13:40:09,511,INFO,common,created directory at: artifacts/data_transformation]
[2024-02-15 13:40:10,637,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-02-15 13:40:10,637,INFO,main,>>>>>> Stage Model Training Stage started <<<<<<]
[2024-02-15 13:40:10,639,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 13:40:10,639,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 13:40:10,639,INFO,common,created directory at: artifacts]
[2024-02-15 13:40:10,639,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-15 13:40:30,263,INFO,main,>>>>>> Stage Model Training Stage completed <<<<<<

x==========]
[2024-02-15 13:45:19,062,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 13:45:20,868,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-02-15 13:45:20,870,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 13:45:20,871,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 13:45:20,871,INFO,common,created directory at: artifacts]
[2024-02-15 13:45:20,871,INFO,common,created directory at: artifacts/data_ingestion]
[2024-02-15 13:45:20,872,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-02-15 13:45:21,069,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-02-15 13:45:21,069,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-02-15 13:45:21,070,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 13:45:21,071,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 13:45:21,071,INFO,common,created directory at: artifacts]
[2024-02-15 13:45:21,071,INFO,common,created directory at: artifacts/data_validation]
[2024-02-15 13:45:21,071,INFO,data_validation,Data Validation Status: True]
[2024-02-15 13:45:21,071,INFO,data_validation,Data Validation Status: True]
[2024-02-15 13:45:21,072,INFO,data_validation,Data Validation Status: True]
[2024-02-15 13:45:21,072,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-02-15 13:45:21,072,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-02-15 13:45:21,073,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 13:45:21,074,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 13:45:21,074,INFO,common,created directory at: artifacts]
[2024-02-15 13:45:21,074,INFO,common,created directory at: artifacts/data_transformation]
[2024-02-15 13:45:22,070,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-02-15 13:45:22,070,INFO,main,>>>>>> Stage Model Training Stage started <<<<<<]
[2024-02-15 13:45:22,072,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 13:45:22,072,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 13:45:22,072,INFO,common,created directory at: artifacts]
[2024-02-15 13:45:22,073,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-15 13:45:35,671,INFO,main,>>>>>> Stage Model Training Stage completed <<<<<<

x==========]
[2024-02-15 14:52:18,972,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 14:52:20,714,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 14:52:20,714,ERROR,main,ModelEvaluationPipeline.main() takes 0 positional arguments but 1 was given]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 60, in <module>
    model_evaluater.main()
TypeError: ModelEvaluationPipeline.main() takes 0 positional arguments but 1 was given
[2024-02-15 14:55:01,140,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 14:55:02,685,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 14:55:02,686,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 14:55:02,687,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 14:55:02,687,INFO,common,created directory at: artifacts]
[2024-02-15 14:55:02,687,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 14:55:10,285,ERROR,main,'article']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 60, in <module>
    model_evaluater.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 16, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 14, in main
    model_evaluator.evaluate()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation.py", line 67, in evaluate
    score = self.calculate_metric_on_test_data(metric=rouge_metric,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation.py", line 27, in calculate_metric_on_test_data
    dataset[column_text], batch_size))
    ~~~~~~~^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/dataset_dict.py", line 74, in __getitem__
    return super().__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'article'
[2024-02-15 15:07:07,302,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 15:07:09,019,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 15:07:09,020,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 15:07:09,021,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 15:07:09,021,INFO,common,created directory at: artifacts]
[2024-02-15 15:07:09,021,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 15:07:18,688,ERROR,main,CUDA out of memory. Tried to allocate 64.00 MiB. GPU 0 has a total capacty of 3.82 GiB of which 20.56 MiB is free. Including non-PyTorch memory, this process has 3.79 GiB memory in use. Of the allocated memory 2.89 GiB is allocated by PyTorch, and 20.21 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 60, in <module>
    model_evaluater.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 16, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 14, in main
    model_evaluator.evaluate()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation.py", line 68, in evaluate
    score = self.calculate_metric_on_test_ds(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation.py", line 34, in calculate_metric_on_test_ds
    summaries = model.generate(input_ids=inputs["input_ids"].to(device),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/generation/utils.py", line 1558, in generate
    return self.beam_search(
           ^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/generation/utils.py", line 2942, in beam_search
    outputs = self(
              ^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 1358, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 1220, in forward
    decoder_outputs = self.decoder(
                      ^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 1052, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 431, in forward
    hidden_states, cross_attn_weights, cross_attn_present_key_value = self.encoder_attn(
                                                                      ^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 182, in forward
    key_states = self._shape(self.k_proj(key_value_states), -1, bsz)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/models/pegasus/modeling_pegasus.py", line 147, in _shape
    return tensor.view(bsz, seq_len, self.num_heads, self.head_dim).transpose(1, 2).contiguous()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 0 has a total capacty of 3.82 GiB of which 20.56 MiB is free. Including non-PyTorch memory, this process has 3.79 GiB memory in use. Of the allocated memory 2.89 GiB is allocated by PyTorch, and 20.21 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2024-02-15 15:33:52,349,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 15:33:52,962,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 15:33:52,964,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 15:33:52,965,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 15:33:52,965,INFO,common,created directory at: artifacts]
[2024-02-15 15:33:52,965,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 15:33:58,794,ERROR,main,"Column article not in the dataset. Current columns in the dataset: ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels']"]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 60, in <module>
    model_evaluater.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 16, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 14, in main
    model_evaluator.evaluate(device="cpu")
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation.py", line 68, in evaluate
    score = self.calculate_metric_on_test_data(metric=rouge_metric,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation.py", line 28, in calculate_metric_on_test_data
    dataset[column_text], batch_size))
    ~~~~~~~^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 2800, in __getitem__
    return self._getitem(key)
           ^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 2784, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/formatting/formatting.py", line 580, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/formatting/formatting.py", line 520, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column article not in the dataset. Current columns in the dataset: ['id', 'dialogue', 'summary', 'input_ids', 'attention_mask', 'labels']"
[2024-02-15 15:36:32,415,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 15:36:33,141,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 15:36:33,142,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 15:36:33,143,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 15:36:33,143,INFO,common,created directory at: artifacts]
[2024-02-15 15:36:33,143,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 15:36:39,738,ERROR,main,'total' is an invalid keyword argument for zip()]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 60, in <module>
    model_evaluater.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 16, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 14, in main
    model_evaluator.evaluate(device="cpu")
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation.py", line 68, in evaluate
    score = self.calculate_metric_on_test_data(metric=rouge_metric,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation.py", line 35, in calculate_metric_on_test_data
    zip(article_batches, target_batches,
TypeError: 'total' is an invalid keyword argument for zip()
[2024-02-15 15:41:23,802,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 15:41:38,052,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 15:41:38,465,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 15:41:38,467,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 15:41:38,467,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 15:41:38,467,INFO,common,created directory at: artifacts]
[2024-02-15 15:41:38,468,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 15:41:38,468,ERROR,main,ModelEvaluation.evaluate() got an unexpected keyword argument 'device']
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 60, in <module>
    model_evaluater.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 16, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 14, in main
    model_evaluator.evaluate(device="cpu")
TypeError: ModelEvaluation.evaluate() got an unexpected keyword argument 'device'
[2024-02-15 15:42:11,282,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 15:42:11,700,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 15:42:11,702,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 15:42:11,703,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 15:42:11,704,INFO,common,created directory at: artifacts]
[2024-02-15 15:42:11,704,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 15:44:32,646,INFO,rouge_scorer,Using default tokenizer.]
[2024-02-15 15:44:32,904,INFO,main,>>>>>> Stage Model Evaluation Stage completed <<<<<<

x==========]
[2024-02-15 15:47:45,284,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 15:47:45,923,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 15:47:45,925,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 15:47:45,926,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 15:47:45,926,INFO,common,created directory at: artifacts]
[2024-02-15 15:47:45,926,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 15:47:51,912,ERROR,main,'total' is an invalid keyword argument for zip()]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 60, in <module>
    model_evaluater.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 22, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 20, in main
    model_evaluator_copy.evaluate(device="cpu")
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation_copy.py", line 68, in evaluate
    score = self.calculate_metric_on_test_data(metric=rouge_metric,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation_copy.py", line 35, in calculate_metric_on_test_data
    zip(article_batches, target_batches,
TypeError: 'total' is an invalid keyword argument for zip()
[2024-02-15 15:49:24,781,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 15:49:25,335,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 15:49:25,336,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 15:49:25,337,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 15:49:25,337,INFO,common,created directory at: artifacts]
[2024-02-15 15:49:25,337,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 18:54:33,209,INFO,rouge_scorer,Using default tokenizer.]
[2024-02-15 18:54:34,509,ERROR,main,dict expected at most 1 argument, got 2]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 60, in <module>
    model_evaluater.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 22, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 20, in main
    model_evaluator_copy.evaluate(device="cpu")
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation_copy.py", line 77, in evaluate
    rouge_dict = dict(dict(rn, score[rn].mid.fmeasure)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation_copy.py", line 77, in <genexpr>
    rouge_dict = dict(dict(rn, score[rn].mid.fmeasure)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dict expected at most 1 argument, got 2
[2024-02-15 19:32:21,714,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 19:32:22,320,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 19:32:22,322,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 19:32:22,323,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 19:32:22,323,INFO,common,created directory at: artifacts]
[2024-02-15 19:32:22,323,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 19:32:53,033,ERROR,main,Mismatch in the number of predictions (1) and references (2)]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 60, in <module>
    model_evaluater.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 22, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_05_model_evaluation.py", line 20, in main
    model_evaluator_copy.evaluate(device="cpu")
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation_copy.py", line 68, in evaluate
    score = self.calculate_metric_on_test_data(metric=rouge_metric,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_evaluation_copy.py", line 53, in calculate_metric_on_test_data
    metric.add_batch(predictions=decoded_summaries,
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/datasets/metric.py", line 520, in add_batch
    raise ValueError(error_msg) from None
ValueError: Mismatch in the number of predictions (1) and references (2)
[2024-02-15 19:35:10,066,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 19:35:10,622,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 19:35:10,624,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 19:35:10,624,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 19:35:10,625,INFO,common,created directory at: artifacts]
[2024-02-15 19:35:10,625,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 19:37:29,513,INFO,rouge_scorer,Using default tokenizer.]
[2024-02-15 19:37:29,757,INFO,main,>>>>>> Stage Model Evaluation Stage completed <<<<<<

x==========]
[2024-02-15 19:39:20,622,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 19:39:33,797,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 19:40:47,009,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 19:40:47,432,INFO,main,>>>>>> Stage Model Evaluation Stage started <<<<<<]
[2024-02-15 19:40:47,434,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 19:40:47,435,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 19:40:47,435,INFO,common,created directory at: artifacts]
[2024-02-15 19:40:47,435,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 19:43:12,639,INFO,rouge_scorer,Using default tokenizer.]
[2024-02-15 19:43:12,899,INFO,main,>>>>>> Stage Model Evaluation Stage completed <<<<<<

x==========]
[2024-02-15 20:08:26,196,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:08:26,198,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:08:26,199,INFO,common,created directory at: artifacts]
[2024-02-15 20:08:26,199,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:14:56,031,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:14:56,042,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:14:56,042,INFO,common,created directory at: artifacts]
[2024-02-15 20:14:56,042,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:26:39,919,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:26:39,920,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:26:39,921,INFO,common,created directory at: artifacts]
[2024-02-15 20:26:39,921,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:28:04,921,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:28:04,924,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:28:04,925,INFO,common,created directory at: artifacts]
[2024-02-15 20:28:04,925,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:29:08,869,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:29:08,871,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:29:08,872,INFO,common,created directory at: artifacts]
[2024-02-15 20:29:08,872,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:30:58,307,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:30:58,309,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:30:58,310,INFO,common,created directory at: artifacts]
[2024-02-15 20:30:58,310,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:32:12,511,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:32:12,514,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:32:12,514,INFO,common,created directory at: artifacts]
[2024-02-15 20:32:12,515,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:32:15,330,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:32:15,332,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:32:15,332,INFO,common,created directory at: artifacts]
[2024-02-15 20:32:15,333,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:34:08,582,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:34:08,584,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:34:08,584,INFO,common,created directory at: artifacts]
[2024-02-15 20:34:08,584,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:45:31,278,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:45:31,280,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:45:31,280,INFO,common,created directory at: artifacts]
[2024-02-15 20:45:31,281,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:49:07,729,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-15 20:49:08,346,INFO,main,>>>>>> Stage Data Ingestion Stage started <<<<<<]
[2024-02-15 20:49:08,348,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:49:08,349,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:49:08,349,INFO,common,created directory at: artifacts]
[2024-02-15 20:49:08,349,INFO,common,created directory at: artifacts/data_ingestion]
[2024-02-15 20:49:08,349,INFO,data_ingestion,File already exits of size: ~ 23073 KB]
[2024-02-15 20:49:08,536,INFO,main,>>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========]
[2024-02-15 20:49:08,536,INFO,main,>>>>>> Stage Data Validation Stage started <<<<<<]
[2024-02-15 20:49:08,537,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:49:08,538,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:49:08,538,INFO,common,created directory at: artifacts]
[2024-02-15 20:49:08,538,INFO,common,created directory at: artifacts/data_validation]
[2024-02-15 20:49:08,538,INFO,data_validation,Data Validation Status: True]
[2024-02-15 20:49:08,538,INFO,data_validation,Data Validation Status: True]
[2024-02-15 20:49:08,539,INFO,data_validation,Data Validation Status: True]
[2024-02-15 20:49:08,539,INFO,main,>>>>>> Stage Data Validation Stage completed <<<<<<

x==========]
[2024-02-15 20:49:08,539,INFO,main,>>>>>> Stage Data Transformation Stage started <<<<<<]
[2024-02-15 20:49:08,540,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:49:08,540,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:49:08,540,INFO,common,created directory at: artifacts]
[2024-02-15 20:49:08,540,INFO,common,created directory at: artifacts/data_transformation]
[2024-02-15 20:49:09,719,INFO,main,>>>>>> Stage Data Transformation Stage completed <<<<<<

x==========]
[2024-02-15 20:49:09,720,INFO,main,>>>>>> Stage Model Training Stage started <<<<<<]
[2024-02-15 20:49:09,721,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:49:09,722,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:49:09,722,INFO,common,created directory at: artifacts]
[2024-02-15 20:49:09,722,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-15 20:49:22,962,ERROR,main,CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 49, in <module>
    model_trainer.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 19, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 17, in main
    model_trainer.train()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_trainer.py", line 43, in train
    trainer = Trainer(
              ^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 459, in __init__
    self._move_model_to_device(model, args.device)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 693, in _move_model_to_device
    model = model.to(device)
            ^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2595, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2024-02-15 20:49:55,929,INFO,server,Started server process [67854]]
[2024-02-15 20:49:55,929,INFO,on,Waiting for application startup.]
[2024-02-15 20:49:55,929,INFO,on,Application startup complete.]
[2024-02-15 20:49:55,929,INFO,server,Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)]
[2024-02-15 20:50:36,061,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 20:50:36,063,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 20:50:36,063,INFO,common,created directory at: artifacts]
[2024-02-15 20:50:36,063,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-15 20:50:42,323,ERROR,h11_impl,Exception in ASGI application
]
Traceback (most recent call last):
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/app.py", line 46, in predict_route
    raise e
  File "/home/dephinate/ASU/TextSummarization/app.py", line 43, in predict_route
    pred = pred_pipe.predict(text=text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/prediction.py", line 16, in predict
    pipe = pipeline("summarization", model=self.config.model_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/pipelines/__init__.py", line 1070, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/pipelines/text2text_generation.py", line 67, in __init__
    super().__init__(*args, **kwargs)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/pipelines/base.py", line 840, in __init__
    self.model.to(self.device)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2595, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2024-02-15 21:09:11,590,INFO,server,Shutting down]
[2024-02-15 21:09:11,691,INFO,on,Waiting for application shutdown.]
[2024-02-15 21:09:11,691,INFO,on,Application shutdown complete.]
[2024-02-15 21:09:11,691,INFO,server,Finished server process [67854]]
[2024-02-15 21:09:18,349,INFO,server,Started server process [69629]]
[2024-02-15 21:09:18,349,INFO,on,Waiting for application startup.]
[2024-02-15 21:09:18,349,INFO,on,Application startup complete.]
[2024-02-15 21:09:18,349,INFO,server,Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)]
[2024-02-15 21:09:23,180,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-15 21:09:23,181,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-15 21:09:23,181,INFO,common,created directory at: artifacts]
[2024-02-15 21:09:23,181,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-16 02:27:58,739,INFO,server,Shutting down]
[2024-02-16 02:27:58,848,INFO,on,Waiting for application shutdown.]
[2024-02-16 02:27:58,848,INFO,on,Application shutdown complete.]
[2024-02-16 02:27:58,848,INFO,server,Finished server process [69629]]
[2024-02-16 02:29:36,020,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-16 02:29:36,624,INFO,main,>>>>>> Stage Model Training Stage started <<<<<<]
[2024-02-16 02:29:36,626,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-16 02:29:36,627,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-16 02:29:36,627,INFO,common,created directory at: artifacts]
[2024-02-16 02:29:36,627,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-16 02:29:48,008,ERROR,main,CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 49, in <module>
    model_trainer.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 19, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 17, in main
    model_trainer.train()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_trainer.py", line 43, in train
    trainer = Trainer(
              ^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 459, in __init__
    self._move_model_to_device(model, args.device)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 693, in _move_model_to_device
    model = model.to(device)
            ^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2595, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2024-02-16 02:38:22,862,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-16 02:38:36,061,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-16 02:38:36,487,INFO,main,>>>>>> Stage Model Training Stage started <<<<<<]
[2024-02-16 02:38:36,489,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-16 02:38:36,489,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-16 02:38:36,490,INFO,common,created directory at: artifacts]
[2024-02-16 02:38:36,490,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-16 02:38:48,485,ERROR,main,CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
]
Traceback (most recent call last):
  File "/home/dephinate/ASU/TextSummarization/main.py", line 49, in <module>
    model_trainer.main()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 19, in main
    raise e
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/pipeline/stage_04_model_trainer.py", line 17, in main
    model_trainer.train()
  File "/home/dephinate/ASU/TextSummarization/src/TextSummarizer/components/model_trainer.py", line 41, in train
    trainer = Trainer(model=model_pegasus, args=trainer_args,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 459, in __init__
    self._move_model_to_device(model, args.device)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/trainer.py", line 693, in _move_model_to_device
    model = model.to(device)
            ^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2595, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/dephinate/miniconda3/envs/texts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2024-02-16 02:41:19,001,INFO,config,PyTorch version 2.1.2 available.]
[2024-02-16 02:41:19,579,INFO,main,>>>>>> Stage Model Training Stage started <<<<<<]
[2024-02-16 02:41:19,581,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-16 02:41:19,582,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-16 02:41:19,582,INFO,common,created directory at: artifacts]
[2024-02-16 02:41:19,582,INFO,common,created directory at: artifacts/model_trainer]
[2024-02-16 02:46:55,673,INFO,server,Started server process [85077]]
[2024-02-16 02:46:55,674,INFO,on,Waiting for application startup.]
[2024-02-16 02:46:55,674,INFO,on,Application startup complete.]
[2024-02-16 02:46:55,674,INFO,server,Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)]
[2024-02-16 02:47:20,043,INFO,common,yaml file config/config.yaml loaded successfully]
[2024-02-16 02:47:20,045,INFO,common,yaml file params.yaml loaded successfully]
[2024-02-16 02:47:20,045,INFO,common,created directory at: artifacts]
[2024-02-16 02:47:20,045,INFO,common,created directory at: artifacts/model_evaluation]
[2024-02-16 02:49:16,996,INFO,server,Shutting down]
[2024-02-16 02:49:17,104,INFO,on,Waiting for application shutdown.]
[2024-02-16 02:49:17,104,INFO,on,Application shutdown complete.]
[2024-02-16 02:49:17,104,INFO,server,Finished server process [85077]]
